export const FETCH_PRODUCTS_START="FETCH_PRODUCTS_START";
export const SET_CATEGORY="SET_CATEGORY";
export const SET_MAX_PRICE="SET_MAX_PRICE";
export const FETCH_PRODUCTS_ERROR="FETCH_PRODUCTS_ERROR";
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS";

